### ISSUE TITLE
PDF generation from node-webkit on PC

### ISSUE THREAD

**Issue by stdi-multimedia** [rse/node-prince#1]
Hi, i've got some trouble implementing that function in node-webkit.
Everything works fine when my app is executed on OSX platform.
However the PDF can't be generated when i test it on a PC (win7 and winXP).

I don't think that it could be a question of permission because i am able to create files/folders from node-webkit.

The error returned by the node-webkit console is the following one :
"Error: err >= 0
at exports._errnoException (util.js:676:20)
at ChildProcess.spawn (child_process.js:973:11)
at exports.spawn (child_process.js:753:9)
at Object.exports.execFile (child_process.js:608:15)
at eval (myProject\Ressources\node_modules\prince\prince-api.js:242:27)
at doResolve (myProject\Ressources\node_modules\prince\node_modules\promise\core.js:91:5)
at new Promise (myProject\Ressources\node_modules\prince\node_modules\promise\core.js:71:3)
at Prince._execute (myProjectRessources\node_modules\prince\prince-api.js:237:12)
at Prince.execute (myProject\Ressources\node_modules\prince\prince-api.js:283:17)
at eval (file:///myProject/Ressources/js/HtmlToPdf.js:102:10)"

Thanks for your help!
STDI-multimedia

**Comment by rse** [comment]
AFAIK this was fixed by the commit related to #2.
