### ISSUE TITLE
Unable to install on Mac OS 10.13.1 (High sierra)

### ISSUE THREAD

**Issue by revdavethompson** [rse/node-prince#17]
Attempted to install prince gem, but keep receiving the following errors.

Using Node 0.11.16

[npm-debug.log](https://github.com/rse/node-prince/files/1366370/npm-debug.log)

```
[master] ~/Projects/node-prince: npm install
npm WARN engine request@2.81.0: wanted: {"node":">= 4"} (current: {"node":"0.11.16","npm":"2.3.0"})
npm WARN engine grunt-eslint@20.1.0: wanted: {"node":">=4"} (current: {"node":"0.11.16","npm":"2.3.0"})
npm WARN engine tar@4.0.1: wanted: {"node":">=4.5"} (current: {"node":"0.11.16","npm":"2.3.0"})
npm WARN engine chalk@2.1.0: wanted: {"node":">=4"} (current: {"node":"0.11.16","npm":"2.3.0"})
npm WARN engine eslint@4.8.0: wanted: {"node":">=4"} (current: {"node":"0.11.16","npm":"2.3.0"})
npm WARN engine ansi-styles@3.2.0: wanted: {"node":">=4"} (current: {"node":"0.11.16","npm":"2.3.0"})
npm WARN engine supports-color@4.4.0: wanted: {"node":">=4"} (current: {"node":"0.11.16","npm":"2.3.0"})
npm WARN engine form-data@2.1.4: wanted: {"node":">= 0.12"} (current: {"node":"0.11.16","npm":"2.3.0"})
npm WARN engine har-validator@4.2.1: wanted: {"node":">=4"} (current: {"node":"0.11.16","npm":"2.3.0"})
npm WARN engine har-schema@1.0.5: wanted: {"node":">=4"} (current: {"node":"0.11.16","npm":"2.3.0"})
npm WARN engine co@4.6.0: wanted: {"iojs":">= 1.0.0","node":">= 0.12.0"} (current: {"node":"0.11.16","npm":"2.3.0"})
npm WARN engine strip-ansi@4.0.0: wanted: {"node":">=4"} (current: {"node":"0.11.16","npm":"2.3.0"})
npm WARN engine eslint-scope@3.7.1: wanted: {"node":">=4.0.0"} (current: {"node":"0.11.16","npm":"2.3.0"})
npm WARN engine pluralize@7.0.0: wanted: {"node":">=4"} (current: {"node":"0.11.16","npm":"2.3.0"})
npm WARN engine ansi-regex@3.0.0: wanted: {"node":">=4"} (current: {"node":"0.11.16","npm":"2.3.0"})
npm WARN engine external-editor@2.0.5: wanted: {"node":">=0.12"} (current: {"node":"0.11.16","npm":"2.3.0"})
npm WARN engine string-width@2.1.1: wanted: {"node":">=4"} (current: {"node":"0.11.16","npm":"2.3.0"})
npm WARN engine run-async@2.3.0: wanted: {"node":">=0.12.0"} (current: {"node":"0.11.16","npm":"2.3.0"})
npm WARN engine ansi-escapes@3.0.0: wanted: {"node":">=4"} (current: {"node":"0.11.16","npm":"2.3.0"})
npm WARN engine cli-cursor@2.1.0: wanted: {"node":">=4"} (current: {"node":"0.11.16","npm":"2.3.0"})
npm WARN engine figures@2.0.0: wanted: {"node":">=4"} (current: {"node":"0.11.16","npm":"2.3.0"})
npm WARN engine string-width@2.1.1: wanted: {"node":">=4"} (current: {"node":"0.11.16","npm":"2.3.0"})
npm WARN engine slice-ansi@1.0.0: wanted: {"node":">=4"} (current: {"node":"0.11.16","npm":"2.3.0"})
npm WARN engine restore-cursor@2.0.0: wanted: {"node":">=4"} (current: {"node":"0.11.16","npm":"2.3.0"})
npm WARN engine is-fullwidth-code-point@2.0.0: wanted: {"node":">=4"} (current: {"node":"0.11.16","npm":"2.3.0"})
npm WARN engine is-fullwidth-code-point@2.0.0: wanted: {"node":">=4"} (current: {"node":"0.11.16","npm":"2.3.0"})
npm WARN engine is-fullwidth-code-point@2.0.0: wanted: {"node":">=4"} (current: {"node":"0.11.16","npm":"2.3.0"})
npm WARN engine onetime@2.0.1: wanted: {"node":">=4"} (current: {"node":"0.11.16","npm":"2.3.0"})
npm WARN engine esprima@4.0.0: wanted: {"node":">=4"} (current: {"node":"0.11.16","npm":"2.3.0"})
npm WARN engine mimic-fn@1.1.0: wanted: {"node":">=4"} (current: {"node":"0.11.16","npm":"2.3.0"})
npm WARN engine co@4.6.0: wanted: {"iojs":">= 1.0.0","node":">= 0.12.0"} (current: {"node":"0.11.16","npm":"2.3.0"})

> prince@1.4.3 install /Users/dave/Projects/node-prince
> node ./prince-npm.js install

/Users/dave/Projects/node-prince/node_modules/chalk/index.js:2
const escapeStringRegexp = require('escape-string-regexp');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/dave/Projects/node-prince/prince-npm.js:46:21)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

npm ERR! Darwin 17.2.0
npm ERR! argv "/Users/dave/.nvm/v0.11.16/bin/node" "/Users/dave/.nvm/v0.11.16/bin/npm" "install"
npm ERR! node v0.11.16
npm ERR! npm  v2.3.0
npm ERR! code ELIFECYCLE
npm ERR! prince@1.4.3 install: `node ./prince-npm.js install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the prince@1.4.3 install script 'node ./prince-npm.js install'.
npm ERR! This is most likely a problem with the prince package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./prince-npm.js install
npm ERR! You can get their info via:
npm ERR!     npm owner ls prince
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/dave/Projects/node-prince/npm-debug.log
[npm-debug.log](https://github.com/rse/node-prince/files/1366372/npm-debug.log)

```

**Comment by revdavethompson** [comment]
Please disregard. Was using an outdated node version
