### ISSUE TITLE
installation error on Azure

### ISSUE THREAD

**Issue by dwhieb** [rse/node-prince#21]
I'm attempting to install node-prince on an Azure web app (so running Windows IIS), and I receive the following error:

```
> prince@1.4.8 install D:\home\site\wwwroot\node_modules\prince
> node ./prince-npm.js install


D:\home\site\wwwroot\node_modules\prince\node_modules\boom\lib\index.js:5
const Hoek = require('hoek');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (D:\home\site\wwwroot\node_modules\prince\node_modules\hawk\lib\index.js:5:33)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 8
npm ERR! prince@1.4.8 install: `node ./prince-npm.js install`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the prince@1.4.8 install script.
```

I'm running the app using Node v8.x. Any ideas how I might fix this error? Thanks!

**Comment by dwhieb** [comment]
You can disregard this - it turns out my virtual machine was not in fact running Node v8.x.
